language: node_js
node_js:
- 10.16.1
cache:
    apt: true
    directories:
        - node_modules
branches:
  only:
  - BlogBranch
before_install:
- npm install
install:
- yarn
script:
- hexo clean
- hexo generate
after_success:
- git config --global user.name "WizTonE"
- git config --global user.email "wiztone@gmail.com"
- sed -i'' "/^ *repo/s~github\.com~${GH_TOKEN}@github.com~" _config.yml
- hexo deploy
env:
  global:
notifications:
   slack: wiztone:EuamGeVgka6UbmPowCoNhGUT